import Vue from "vue"
import SkButton from "../../components/SkButton";
import SkButtonGroup from "../../components/SkButtonGroup";
import SkCheckBox from "../../components/SkCheckBox";
import SkCol from "../../components/SkCol";
import SkRow from "../../components/SkRow";
import SkColumn from "../../components/SkColumn";
import SkDatePicker from "../../components/SkDatePicker";
import SkFixedBottom from "../../components/SkFixedBottom";
import SkForm from "../../components/SkForm";
import SkMoney from "../../components/SkMoney";
import SkRadio from "../../components/SkRadio";
import SkSelect from "../../components/SkSelect";
import SkTag from "../../components/SkTag";
import SkTextInput from "../../components/SkTextInput";
import SkTimePicker from "../../components/SkTimePicker";
import SkLayout from "../../components/SkLayout";
import SkPart from "../../components/SkPart";
import SkTable from "../../components/SkTable";
import SkDialog from "../../components/SkDialog";
import SkUpload from "../../components/SkUpload";

Vue.component(SkButton.name, SkButton);
Vue.component(SkButtonGroup.name, SkButtonGroup);
Vue.component(SkCheckBox.name, SkCheckBox);
Vue.component(SkCol.name, SkCol);
Vue.component(SkRow.name, SkRow);
Vue.component(SkColumn.name, SkColumn);
Vue.component(SkDatePicker.name, SkDatePicker);
Vue.component(SkFixedBottom.name, SkFixedBottom);
Vue.component(SkForm.name, SkForm);
Vue.component(SkMoney.name, SkMoney);
Vue.component(SkRadio.name, SkRadio);
Vue.component(SkSelect.name, SkSelect);
Vue.component(SkTable.name, SkTable);
Vue.component(SkTag.name, SkTag);
Vue.component(SkTextInput.name, SkTextInput);
Vue.component(SkTimePicker.name, SkTimePicker);
Vue.component(SkLayout.name, SkLayout);
Vue.component(SkPart.name, SkPart);
Vue.component(SkDialog.name, SkDialog);
Vue.component(SkUpload.name, SkUpload);
